/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateValueDto } from './createValueDto';


export interface CreateCategoryDto { 
    name?: string | null;
    values?: Array<CreateValueDto> | null;
}

