/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateColumnDto } from './createColumnDto';


export interface CreateLayoutDto { 
    name?: string | null;
    columns?: Array<CreateColumnDto> | null;
}

