/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReadValueDto } from './readValueDto';


export interface ReadCategoryDto { 
    id?: number;
    name?: string | null;
    values?: Array<ReadValueDto> | null;
}

