/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReadColumnDto } from './readColumnDto';


export interface ReadLayoutDto { 
    id?: number;
    name?: string | null;
    isArchieved?: boolean;
    columns?: Array<ReadColumnDto> | null;
}

