/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReadCategoryDto } from './readCategoryDto';


export interface ReadColumnDto { 
    id?: number;
    position?: number;
    name?: string | null;
    type?: string | null;
    category?: ReadCategoryDto;
}

