/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateColumnDto { 
    position?: number;
    name?: string | null;
    type?: string | null;
    categoryId?: number | null;
}

