/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryValueUpdateDto } from './categoryValueUpdateDto';


export interface CategoryUpdateDto { 
    id?: string;
    name?: string | null;
    values?: Array<CategoryValueUpdateDto> | null;
}

