/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryValueCreateDto } from './categoryValueCreateDto';


export interface CategoryCreateDto { 
    name?: string | null;
    values?: Array<CategoryValueCreateDto> | null;
}

