/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColumnType } from './columnType';
import { CategoryReadDto } from './categoryReadDto';


export interface ColumnReadDto { 
    id?: string;
    position?: number;
    name?: string | null;
    type?: ColumnType;
    categoryId?: string | null;
    category?: CategoryReadDto;
}
export namespace ColumnReadDto {
}


