/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColumnUpdateDto } from './columnUpdateDto';


export interface LayoutUpdateDto { 
    id?: string;
    name?: string | null;
    isArchived?: boolean;
    columns?: Array<ColumnUpdateDto> | null;
}

