FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine
WORKDIR /app

ARG CONFIGURATION=Release

ENV ASPNETCORE_ENVIRONMENT=Testing \
    DOTNET_RUNNING_IN_CONTAINER=true

COPY S2Retro.sln ./
COPY src/Api/S2Retro.Api.csproj ./src/Api/
COPY src/Infrastructure/S2Retro.Infrastructure.csproj ./src/Infrastructure/
COPY tests/S2Retro.UnitTests/S2Retro.UnitTests.csproj ./tests/S2Retro.UnitTests/
COPY tests/S2Retro.IntegrationTests/S2Retro.IntegrationTests.csproj ./tests/S2Retro.IntegrationTests/
COPY src/Modules/ ./src/Modules/

RUN dotnet restore

COPY . .

RUN dotnet build --configuration $CONFIGURATION --no-restore

CMD ["dotnet", "test", "--configuration", "Release", "--logger:console;verbosity=normal", "--no-build"]