// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S2Retro.Infrastructure.Data;

#nullable disable

namespace S2Retro.Infrastructure.Migrations
{
    [DbContext(typeof(S2RetroDbContext))]
    [Migration("20251106142449_AddRetroBoard")]
    partial class AddRetroBoard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.Instance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EntryPhaseEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EntryPhaseStart")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("InstanceCategories");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceCategoryValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("InstanceCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("InstanceCategoryId");

                    b.ToTable("InstanceCategoryValues");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceCell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("InstanceCategoryValueId")
                        .HasColumnType("char(36)");

                    b.Property<double?>("NumberValue")
                        .HasColumnType("double");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("RowId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TextValue")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("InstanceCategoryValueId");

                    b.HasIndex("RowId");

                    b.ToTable("InstanceCells");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("InstanceCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstanceCategoryId");

                    b.HasIndex("InstanceId");

                    b.ToTable("InstanceColumns");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("InstanceRows");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.Instance", b =>
                {
                    b.HasOne("S2Retro.Modules.RetroBoard.Domain.Entities.Board", "Board")
                        .WithMany("Instances")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceCategoryValue", b =>
                {
                    b.HasOne("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceCategory", "Category")
                        .WithMany("Values")
                        .HasForeignKey("InstanceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceCell", b =>
                {
                    b.HasOne("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceCategoryValue", "CategoryValue")
                        .WithMany()
                        .HasForeignKey("InstanceCategoryValueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceRow", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryValue");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceColumn", b =>
                {
                    b.HasOne("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("InstanceCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("S2Retro.Modules.RetroBoard.Domain.Entities.Instance", "Instance")
                        .WithMany("Columns")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceRow", b =>
                {
                    b.HasOne("S2Retro.Modules.RetroBoard.Domain.Entities.Instance", "Instance")
                        .WithMany("Rows")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.Board", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.Instance", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceCategory", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("S2Retro.Modules.RetroBoard.Domain.Entities.InstanceRow", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
