/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColumnType } from './columnType';
import { CategoryCreateDto } from './categoryCreateDto';


export interface ColumnCreateDto { 
    position?: number;
    name?: string | null;
    type?: ColumnType;
    categoryId?: string | null;
    category?: CategoryCreateDto;
}
export namespace ColumnCreateDto {
}


