/**
 * S2Retro.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColumnType } from './columnType';
import { CategoryUpdateDto } from './categoryUpdateDto';


export interface ColumnUpdateDto { 
    id?: string;
    position?: number;
    name?: string | null;
    type?: ColumnType;
    categoryId?: string | null;
    category?: CategoryUpdateDto;
}
export namespace ColumnUpdateDto {
}


