/**
 * S2Retro.Presentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstanceCellCreateDto } from './instanceCellCreateDto';


export interface InstanceRowCreateDto { 
    position?: number;
    instanceId?: string;
    cells?: Array<InstanceCellCreateDto> | null;
}

