/**
 * S2Retro.Presentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstanceCellReadDto } from './instanceCellReadDto';


export interface InstanceRowReadDto { 
    id?: string;
    position?: number;
    instanceId?: string;
    cells?: Array<InstanceCellReadDto> | null;
}

