/**
 * S2Retro.Presentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstanceRowUpdateDto } from './instanceRowUpdateDto';
import { InstanceColumnUpdateDto } from './instanceColumnUpdateDto';
import { InstancePhase } from './instancePhase';


export interface InstanceUpdateDto { 
    id?: string;
    name?: string | null;
    isArchived?: boolean;
    entryPhaseStart?: string;
    entryPhaseEnd?: string | null;
    phase?: InstancePhase;
    boardId?: string;
    columns?: Array<InstanceColumnUpdateDto> | null;
    rows?: Array<InstanceRowUpdateDto> | null;
}
export namespace InstanceUpdateDto {
}


