/**
 * S2Retro.Presentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstanceCategoryValueCreateDto } from './instanceCategoryValueCreateDto';


export interface InstanceCellCreateDto { 
    position?: number;
    textValue?: string | null;
    numberValue?: number | null;
    boolValue?: boolean | null;
    dateValue?: string | null;
    rowId?: string;
    instanceCategoryValueId?: string | null;
    categoryValue?: InstanceCategoryValueCreateDto;
}

