/**
 * S2Retro.Presentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstanceCellUpdateDto } from './instanceCellUpdateDto';


export interface InstanceRowUpdateDto { 
    id?: string;
    position?: number;
    instanceId?: string;
    cells?: Array<InstanceCellUpdateDto> | null;
}

