/**
 * S2Retro.Presentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstanceCategoryValueCreateDto } from './instanceCategoryValueCreateDto';


export interface InstanceCategoryCreateDto { 
    name?: string | null;
    values?: Array<InstanceCategoryValueCreateDto> | null;
}

