/**
 * S2Retro.Presentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstanceCategoryCreateDto } from './instanceCategoryCreateDto';
import { ColumnType } from './columnType';


export interface InstanceColumnCreateDto { 
    position?: number;
    name?: string | null;
    type?: ColumnType;
    instanceId?: string;
    instanceCategoryId?: string | null;
    category?: InstanceCategoryCreateDto;
}
export namespace InstanceColumnCreateDto {
}


