/**
 * S2Retro.Presentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstanceCategoryValueUpdateDto } from './instanceCategoryValueUpdateDto';


export interface InstanceCategoryUpdateDto { 
    id?: string;
    name?: string | null;
    values?: Array<InstanceCategoryValueUpdateDto> | null;
}

